source :rubygems
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
gem "middleman", "~>3.1.4"
gem "redcarpet"
gem "rack-codehighlighter", :git => "git://github.com/wbzyl/rack-codehighlighter.git"
gem "pygments.rb"

